# Base image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the application files
COPY api/api.py .

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port for the API
EXPOSE 8000

# Define the command to run the API
CMD ["python", "api.py"]